"""
Helper Utilities
"""

from typing import Dict, Any, List
from datetime import datetime
import json


def generate_html_report(db, output_path: str):
    """Generate HTML report from graph database."""
    stats = db.get_stats()
    export_data = db.export_json()
    
    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CodeGraph-Lite Report</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #0f172a; color: #e2e8f0; padding: 20px; }}
        .container {{ max-width: 1200px; margin: 0 auto; }}
        h1 {{ color: #a855f7; margin-bottom: 20px; }}
        h2 {{ color: #22d3ee; margin: 20px 0 10px; }}
        .stats {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 15px; margin: 20px 0; }}
        .stat-card {{ background: #1e293b; padding: 20px; border-radius: 10px; border: 1px solid #334155; }}
        .stat-value {{ font-size: 2em; color: #22d3ee; font-weight: bold; }}
        .stat-label {{ color: #94a3b8; margin-top: 5px; }}
        table {{ width: 100%; border-collapse: collapse; margin: 10px 0; }}
        th, td {{ padding: 10px; text-align: left; border-bottom: 1px solid #334155; }}
        th {{ background: #1e293b; color: #a855f7; }}
        tr:hover {{ background: #1e293b; }}
        .kind-function {{ color: #22d3ee; }}
        .kind-class {{ color: #a855f7; }}
        .kind-method {{ color: #f472b6; }}
        .footer {{ margin-top: 40px; padding-top: 20px; border-top: 1px solid #334155; color: #64748b; }}
    </style>
</head>
<body>
    <div class="container">
        <h1>🔮 CodeGraph-Lite Report</h1>
        
        <div class="stats">
            <div class="stat-card">
                <div class="stat-value">{stats['files']}</div>
                <div class="stat-label">Files Indexed</div>
            </div>
            <div class="stat-card">
                <div class="stat-value">{stats['nodes']}</div>
                <div class="stat-label">Total Symbols</div>
            </div>
            <div class="stat-card">
                <div class="stat-value">{stats['edges']}</div>
                <div class="stat-label">Relationships</div>
            </div>
        </div>
        
        <h2>📊 Nodes by Kind</h2>
        <table>
            <tr><th>Kind</th><th>Count</th></tr>
"""
    
    for kind, count in sorted(stats.get('nodes_by_kind', {}).items(), key=lambda x: -x[1]):
        html += f'            <tr><td class="kind-{kind}">{kind}</td><td>{count}</td></tr>\n'
    
    html += """        </table>
        
        <h2>💻 Files by Language</h2>
        <table>
            <tr><th>Language</th><th>Files</th></tr>
"""
    
    for lang, count in sorted(stats.get('files_by_lang', {}).items(), key=lambda x: -x[1]):
        html += f'            <tr><td>{lang}</td><td>{count}</td></tr>\n'
    
    html += f"""        </table>
        
        <div class="footer">
            Generated by CodeGraph-Lite on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
        </div>
    </div>
</body>
</html>
"""
    
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(html)


def generate_markdown_report(db, output_path: str):
    """Generate Markdown report from graph database."""
    stats = db.get_stats()
    
    md = f"""# 🔮 CodeGraph-Lite Report

Generated on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## 📊 Statistics

| Metric | Count |
|--------|-------|
| Files Indexed | {stats['files']} |
| Total Symbols | {stats['nodes']} |
| Relationships | {stats['edges']} |

## 🏷️ Nodes by Kind

| Kind | Count |
|------|-------|
"""
    
    for kind, count in sorted(stats.get('nodes_by_kind', {}).items(), key=lambda x: -x[1]):
        md += f"| {kind} | {count} |\n"
    
    md += "\n## 💻 Files by Language\n\n| Language | Files |\n|----------|-------|\n"
    
    for lang, count in sorted(stats.get('files_by_lang', {}).items(), key=lambda x: -x[1]):
        md += f"| {lang} | {count} |\n"
    
    md += "\n---\n\n*Generated by CodeGraph-Lite*\n"
    
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(md)


def format_symbol_table(symbols: List[Dict[str, Any]], title: str = "Symbols") -> str:
    """Format symbols as a text table."""
    lines = [f"\n{title}:", "-" * 60]
    
    for sym in symbols:
        kind = sym.get('kind', 'unknown')
        name = sym.get('name', '?')
        file = sym.get('file', '?')
        line = sym.get('line', 0)
        
        lines.append(f"  [{kind:10}] {name:30} {file}:{line}")
    
    return "\n".join(lines)


def calculate_complexity(symbol: Dict[str, Any]) -> int:
    """Calculate simple complexity score for a symbol."""
    score = 1
    
    # Add points for various factors
    if symbol.get('docstring'):
        score += 1
    
    if symbol.get('decorators'):
        score += len(symbol['decorators'])
    
    if symbol.get('bases'):
        score += len(symbol['bases'])
    
    # Estimate based on line span
    end_line = symbol.get('end_line', symbol.get('line', 0))
    start_line = symbol.get('line', 0)
    line_span = max(0, end_line - start_line)
    
    if line_span > 50:
        score += 3
    elif line_span > 20:
        score += 2
    elif line_span > 10:
        score += 1
    
    return score


def get_file_icon(language: str) -> str:
    """Get icon for a programming language."""
    icons = {
        'Python': '🐍',
        'JavaScript': '💛',
        'TypeScript': '💙',
        'Java': '☕',
        'Go': '🐹',
        'Rust': '🦀',
        'C': '🔵',
        'C++': '🔷',
        'Ruby': '💎',
        'PHP': '🐘',
        'Swift': '🍎',
        'Kotlin': '🎯',
    }
    return icons.get(language, '📄')


def get_kind_icon(kind: str) -> str:
    """Get icon for a symbol kind."""
    icons = {
        'function': '⚡',
        'class': '🏗️',
        'method': '🔧',
        'variable': '📦',
        'import': '📥',
        'interface': '🔌',
        'constant': '🔒',
        'property': '🏷️',
        'decorator': '🎨',
    }
    return icons.get(kind, '📍')
